export const CHANGE_TAB_INDEX = 'CHANGE_TAB_INDEX';
export const CLEAN_ALL_REDUCERS = 'CLEAN_ALL_REDUCERS';
export const OPEN_DRAWER = 'OPEN_DRAWER';

export const CHANGE_USER = 'CHANGE_USER';

export const CHANGE_ROLES = 'CHANGE_ROLES';
export const CHANGE_ROLE = 'CHANGE_ROLE';
export const CHANGE_USER_ROLE = 'CHANGE_USER_ROLE';

export const CHANGE_USERS = 'CHANGE_USERS';
export const CHANGE_USER_SELECTED = 'CHANGE_USER_SELECTED';

export const CHANGE_SCHOOLS = 'CHANGE_SCHOOLS';
export const CHANGE_SCHOOL = 'CHANGE_SCHOOL';
//Careras
export const CHANGE_CARRERAS = 'CHANGE_CARRERAS';
export const CHANGE_CARRERA = 'CHANGE_CARRERA';
export const CHANGE_AUX_CARRERA = 'CHANGE_AUX_CARRERA';
//Materias
export const CHANGE_MATERIAS = 'CHANGE_MATERIAS';
export const CHANGE_MATERIA = 'CHANGE_MATERIA';

//filtros
export const CHANGE_FACULTAD_SELECCIONADA_FILTRO = 'CHANGE_FACULTAD_SELECCIONADA_FILTRO';
export const CHANGE_CARRERA_SELECCIONADA_FILTRO = 'CHANGE_CARRERA_SELECCIONADA_FILTRO';
export const CHANGE_MATERIA_SELECCIONADA_FILTRO = 'CHANGE_MATERIA_SELECCIONADA_FILTRO';

export const CHANGE_ROLEFUNCS = 'CHANGE_ROLEFUNCS';
