export const routes = {
  home: '/home',
  login: '/login',
  campus: '/users',
  school: '/school',
  subjects: '/subjects',
  reports: '/reports',
  schedule: '/schedule',
  groups: '/groups',
  administration: '/administration',
  roles: '/roles',
  newRole: '/newrole',
  editRole: '/roles/:id',
  account: '/account',
  route404: '/404',
  testUi: '/testui',
  registerUser: '/registerUser',
  editUser: '/users/:id',
};
