export const routes = {
  home: '/home',
  login: '/login',
  campus: '/users',
  career: '/career',
  registerCareer: '/newcareer',
  editCareer: '/career/:id',
  school: '/school',
  registerSchool: '/newschool',
  editSchool: '/school/:id',
  subjects: '/subjects',
  registerMateria: '/newsubjects',
  editMateria: '/subjects/:id',
  reports: '/reports',
  schedule: '/schedule',
  groups: '/groups',
  administration: '/administration',
  roles: '/roles',
  newRole: '/newrole',
  editRole: '/roles/:id',
  account: '/account',
  route404: '/404',
  testUi: '/testui',
  registerUser: '/registerUser',
  editUser: '/users/:id',
};
